import type { Metadata } from "next";
import { ChakraUIProvider } from "../providers/ChakraUIProvider";

import "@/styles/font.css";
import Sidebar from "./components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ChakraUIProvider>
          <Sidebar>{children}</Sidebar>
        </ChakraUIProvider>
      </body>
    </html>
  );
}
